ALTER TABLE public.funnel_daily_records
  ADD COLUMN IF NOT EXISTS ctr           NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpm           NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpc           NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unique_clicks NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unique_ctr    NUMERIC NOT NULL DEFAULT 0;
